<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite id="0" name="/Users/rlamichh/aig/tests/react-login/src/services/user.service.test.js" errors="0" package="/Users/rlamichh/aig/tests/react-login/src/services/user.service.test.js" hostname="localhost" tests="2" failures="2" time="0.729" timestamp="2018-09-25T15:05:18">
    <properties>
    </properties>
    <testcase classname="Test User service" name="check if a fetch promise is returned and localStorage is used in login" time="0">
      <failure message="TypeError: Cannot read property &apos;username&apos; of undefined
    at Object.it (/Users/rlamichh/aig/tests/react-login/src/services/user.service.test.js:34:31)
    at &lt;anonymous&gt;
    at process._tickCallback (internal/process/next_tick.js:188:7)" type="AssertionError">
      </failure>
    </testcase>
    <testcase classname="Test User service" name="check if logout removes `user` item from localStorage" time="0">
      <failure message="Error: expect(received).toEqual(expected)

Expected value to equal:
  true
Received:
  false
    at Object.it (/Users/rlamichh/aig/tests/react-login/src/services/user.service.test.js:41:59)
    at Object.asyncFn (/Users/rlamichh/aig/tests/react-login/node_modules/jest-jasmine2/build/jasmine-async.js:68:30)
    at resolve (/Users/rlamichh/aig/tests/react-login/node_modules/jest-jasmine2/build/queueRunner.js:38:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (/Users/rlamichh/aig/tests/react-login/node_modules/jest-jasmine2/build/queueRunner.js:31:21)
    at Promise.resolve.then.el (/Users/rlamichh/aig/tests/react-login/node_modules/p-map/index.js:46:16)
    at &lt;anonymous&gt;
    at process._tickCallback (internal/process/next_tick.js:188:7)" type="AssertionError">
      </failure>
    </testcase>
    <system-out/>
    <system-err/>
  </testsuite>
  <testsuite id="1" name="/Users/rlamichh/aig/tests/react-login/src/components/HomePage.test.js" errors="0" package="/Users/rlamichh/aig/tests/react-login/src/components/HomePage.test.js" hostname="localhost" tests="1" failures="1" time="0.138" timestamp="2018-09-25T15:05:19">
    <properties>
    </properties>
    <testcase classname="Test HomePage component" name="uses Router for logout functionality" time="0">
      <failure message="AssertionError: expected {} to have a length of 1 but got 0
    at Object.it (/Users/rlamichh/aig/tests/react-login/src/components/HomePage.test.js:17:68)
    at Object.asyncFn (/Users/rlamichh/aig/tests/react-login/node_modules/jest-jasmine2/build/jasmine-async.js:68:30)
    at resolve (/Users/rlamichh/aig/tests/react-login/node_modules/jest-jasmine2/build/queueRunner.js:38:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (/Users/rlamichh/aig/tests/react-login/node_modules/jest-jasmine2/build/queueRunner.js:31:21)
    at Promise.resolve.then.el (/Users/rlamichh/aig/tests/react-login/node_modules/p-map/index.js:46:16)
    at &lt;anonymous&gt;" type="AssertionError">
      </failure>
    </testcase>
    <system-out/>
    <system-err/>
  </testsuite>
  <testsuite id="2" name="/Users/rlamichh/aig/tests/react-login/src/components/RegisterPage.test.js" errors="0" package="/Users/rlamichh/aig/tests/react-login/src/components/RegisterPage.test.js" hostname="localhost" tests="1" failures="0" time="0.428" timestamp="2018-09-25T15:05:19">
    <properties>
    </properties>
    <testcase classname="Test RegisterPage component" name="check route, dispatch and store setup for component" time="0">
    </testcase>
    <system-out/>
    <system-err/>
  </testsuite>
  <testsuite id="3" name="/Users/rlamichh/aig/tests/react-login/src/components/LoginPage.test.js" errors="0" package="/Users/rlamichh/aig/tests/react-login/src/components/LoginPage.test.js" hostname="localhost" tests="2" failures="0" time="0.122" timestamp="2018-09-25T15:05:20">
    <properties>
    </properties>
    <testcase classname="Test LoginPage component" name="check route, dispatch and store setup for component" time="0">
    </testcase>
    <testcase classname="Test LoginPage component" name="" time="0">
    </testcase>
    <system-out/>
    <system-err/>
  </testsuite>
  <testsuite id="4" name="/Users/rlamichh/aig/tests/react-login/src/actions/index.test.js" errors="0" package="/Users/rlamichh/aig/tests/react-login/src/actions/index.test.js" hostname="localhost" tests="4" failures="4" time="0.114" timestamp="2018-09-25T15:05:20">
    <properties>
    </properties>
    <testcase classname="Test Redux Alert Actions" name="uses correct constants" time="0">
      <failure message="Error: expect(received).toEqual(expected)

Expected value to equal:
  {&quot;message&quot;: &quot;Random Success Message&quot;, &quot;type&quot;: &quot;ALERT_SUCCESS&quot;}
Received:
  undefined

Difference:

  Comparing two different types of values. Expected object but received undefined.
    at Object.it (/Users/rlamichh/aig/tests/react-login/src/actions/index.test.js:23:82)
    at Object.asyncFn (/Users/rlamichh/aig/tests/react-login/node_modules/jest-jasmine2/build/jasmine-async.js:68:30)
    at resolve (/Users/rlamichh/aig/tests/react-login/node_modules/jest-jasmine2/build/queueRunner.js:38:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (/Users/rlamichh/aig/tests/react-login/node_modules/jest-jasmine2/build/queueRunner.js:31:21)
    at Promise.resolve.then.el (/Users/rlamichh/aig/tests/react-login/node_modules/p-map/index.js:46:16)
    at &lt;anonymous&gt;" type="AssertionError">
      </failure>
    </testcase>
    <testcase classname="Test Authentication via Redux" name="logout uses service and correct constant" time="0">
      <failure message="Error: expect(received).toEqual(expected)

Expected value to equal:
  true
Received:
  false
    at Object.it (/Users/rlamichh/aig/tests/react-login/src/actions/index.test.js:41:64)
    at Object.asyncFn (/Users/rlamichh/aig/tests/react-login/node_modules/jest-jasmine2/build/jasmine-async.js:68:30)
    at resolve (/Users/rlamichh/aig/tests/react-login/node_modules/jest-jasmine2/build/queueRunner.js:38:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (/Users/rlamichh/aig/tests/react-login/node_modules/jest-jasmine2/build/queueRunner.js:31:21)
    at Promise.resolve.then.el (/Users/rlamichh/aig/tests/react-login/node_modules/p-map/index.js:46:16)
    at &lt;anonymous&gt;" type="AssertionError">
      </failure>
    </testcase>
    <testcase classname="Test Authentication via Redux" name="login uses service and correct dispatch logic" time="0">
      <failure message="Error: expect(received).toBe(expected) // Object.is equality

Expected value to be:
  &quot;function&quot;
Received:
  &quot;object&quot;
    at Object.it (/Users/rlamichh/aig/tests/react-login/src/actions/index.test.js:46:89)
    at Object.asyncFn (/Users/rlamichh/aig/tests/react-login/node_modules/jest-jasmine2/build/jasmine-async.js:68:30)
    at resolve (/Users/rlamichh/aig/tests/react-login/node_modules/jest-jasmine2/build/queueRunner.js:38:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (/Users/rlamichh/aig/tests/react-login/node_modules/jest-jasmine2/build/queueRunner.js:31:21)
    at Promise.resolve.then.el (/Users/rlamichh/aig/tests/react-login/node_modules/p-map/index.js:46:16)
    at &lt;anonymous&gt;" type="AssertionError">
      </failure>
    </testcase>
    <testcase classname="Test Authentication via Redux" name="register uses service and correct logic" time="0">
      <failure message="Error: expect(received).toBe(expected) // Object.is equality

Expected value to be:
  &quot;function&quot;
Received:
  &quot;undefined&quot;
    at Object.it (/Users/rlamichh/aig/tests/react-login/src/actions/index.test.js:50:75)
    at Object.asyncFn (/Users/rlamichh/aig/tests/react-login/node_modules/jest-jasmine2/build/jasmine-async.js:68:30)
    at resolve (/Users/rlamichh/aig/tests/react-login/node_modules/jest-jasmine2/build/queueRunner.js:38:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (/Users/rlamichh/aig/tests/react-login/node_modules/jest-jasmine2/build/queueRunner.js:31:21)
    at Promise.resolve.then.el (/Users/rlamichh/aig/tests/react-login/node_modules/p-map/index.js:46:16)
    at &lt;anonymous&gt;" type="AssertionError">
      </failure>
    </testcase>
    <system-out/>
    <system-err/>
  </testsuite>
  <testsuite id="5" name="/Users/rlamichh/aig/tests/react-login/src/App.test.js" errors="0" package="/Users/rlamichh/aig/tests/react-login/src/App.test.js" hostname="localhost" tests="2" failures="0" time="0.136" timestamp="2018-09-25T15:05:20">
    <properties>
    </properties>
    <testcase classname="Test AppComponent" name="check route, dispatch and store setup for component" time="0">
    </testcase>
    <testcase classname="Test AppComponent" name="check for redirections" time="0">
    </testcase>
    <system-out/>
    <system-err/>
  </testsuite>
</testsuites>